"""empty message

Revision ID: 07af6d7cad45
Revises: 2ce583c30dc1
Create Date: 2020-07-11 16:37:25.795719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07af6d7cad45'
down_revision = '2ce583c30dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('dates', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'dates')
    # ### end Alembic commands ###
